name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ReScript
        uses: actions/checkout@v4
        with:
          repository: rescript-lang/rescript-compiler

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3.0.0
        with:
          ocaml-compiler: 5.2.0
          allow-prerelease-opam: true
          opam-pin: false

      - run: opam install . --deps-only

      - run: opam exec -- dune build --display quiet --profile static

      - run: file _build/default/jscomp/bsc/rescript_compiler_main.exe

      - run: _build/default/jscomp/bsc/rescript_compiler_main.exe -v
