name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [
            ubuntu-latest, # x64
            buildjet-2vcpu-ubuntu-2204-arm, # ARM
          ]

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout ReScript
        uses: actions/checkout@v4
        with:
          repository: rescript-lang/rescript-compiler

      - run: update-alternatives --query gcc

      - run: sudo apt install -y --no-install-recommends opam musl-tools

      - run: opam --version

      - run: opam init -y --bare --disable-sandboxing

      - run: opam switch create 5.2.0 --packages ocaml-option-static

      - run: opam install . -y --deps-only

      - run: opam exec -- dune build --display quiet --profile static

      - run: file _build/default/jscomp/bsc/rescript_compiler_main.exe

      - run: _build/default/jscomp/bsc/rescript_compiler_main.exe -v
